name = "download-page"
type = "javascript"

account_id = "b5d1a3835f0dd218f633c7d612935c6b"
workers_dev = true
route = ""
zone_id = ""

kv_namespaces = [ 
         { binding = "MY_KV", id = "dedba216553b445681f5043a2dcaee68", preview_id = "59b38fdd3ea94a7c91122f3ffba1d308" }
]
