on:
  push:
    branches:
      - main
    paths:
      - assets/VERSION

jobs:
  create-release-tag:
    name: Create release tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            const fs = require('fs');
            const version = fs.readFileSync('assets/VERSION', 'utf8').trim();

            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/v${version}`,
              sha: context.sha
            })
