on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
      uses: wangyoucao577/go-release-action@v1.18
      if: startsWith(github.ref, 'refs/tags/')
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        pre_command: go generate
        extra_files: LICENSE
